name: pineaple_pos_client
description: Point of Sale

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1-SNAPSHOT.20220322

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.2.3-RELEASE.20220206

  #Animations
  sliver_fab:
    git:
      url: https://github.com/JesusHdezWaterloo/sliver_fab

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    #Images
    - packages/pineaple_pos_client/assets/images/area_image.png

  uses-material-design: true
