name: pineaple_pos_client
description: Point of Sale

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1-SNAPSHOT.20220322

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Architecture & Management
  get: ^4.5.1
  clean_core:
    path: ../../clean-core-flutter
  #clean_core: ^1.2.3-RELEASE.20220206
  auto_size_text: ^3.0.0

  #Animations
  animations: ^2.0.2
  sliver_fab:
    git:
      url: https://github.com/JesusHdezWaterloo/sliver_fab

  #REST
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 400
    - family: AkayaTelivigala
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf
          weight: 400
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Variable.ttf
          weight: 400

  assets:
    #Images
    - packages/pineaple_pos_client/assets/images/area_image.jpg

  uses-material-design: true
